import { OutputManifestSchema, ScriptJobSchema, VoiceOverJobSchema } from './schemas.mjs';
import { attachScriptVariantsToApprovals } from './workflow-approvals.mjs';

function normalizeSpokenText(text) {
  return text
    .toLocaleLowerCase('en-US')
    .replace(/[^\p{L}\p{N}\s]/gu, '')
    .replace(/\s+/gu, ' ')
    .trim();
}

function calculateTokenSimilarity(left, right) {
  const leftTokens = new Set(normalizeSpokenText(left).split(' ').filter(Boolean));
  const rightTokens = new Set(normalizeSpokenText(right).split(' ').filter(Boolean));
  const intersection = [...leftTokens].filter((token) => rightTokens.has(token)).length;
  const union = new Set([...leftTokens, ...rightTokens]).size;
  return union === 0 ? 1 : intersection / union;
}

export async function generateLocalScriptPreview(options) {
  const sourceManifest = OutputManifestSchema.parse(options.manifest);
  const readiness = await options.scriptAdapter.checkReadiness();
  if (readiness.status !== 'ready') {
    throw new Error(readiness.detail);
  }

  const product = sourceManifest.products[0];
  const scriptVariants = [];
  for (const scriptJob of sourceManifest.script_jobs) {
    const variant = await options.scriptAdapter.generateVariant({
      product,
      scriptJob,
      runAt: sourceManifest.run_at,
    });
    const normalized = normalizeSpokenText(variant.spoken_text);
    if (scriptVariants.some((existing) => {
      const existingNormalized = normalizeSpokenText(existing.spoken_text);
      return existingNormalized === normalized
        || calculateTokenSimilarity(existing.spoken_text, variant.spoken_text) >= 0.82;
    })) {
      throw new Error(
        `Local script generation produced duplicate or near-duplicate wording for angle ${scriptJob.angle}; operator review payload was not created.`,
      );
    }
    scriptVariants.push(variant);
  }

  const scriptJobs = sourceManifest.script_jobs.map((job) => ScriptJobSchema.parse({
    ...job,
    model_plan: { ...job.model_plan, execute: true },
    status: 'completed',
  }));
  const variantByJobId = new Map(scriptJobs.map((job, index) => [
    job.script_job_id,
    scriptVariants[index],
  ]));
  const voiceOverJobs = sourceManifest.voice_over_jobs.map((job) => VoiceOverJobSchema.parse({
    ...job,
    script_variant_id: variantByJobId.get(job.script_job_id).script_variant_id,
    blockers: [
      'script_variant_approval_pending',
      'local_tts_execution_not_enabled',
    ],
  }));
  const workflowApprovals = attachScriptVariantsToApprovals(
    sourceManifest.workflow_approvals,
    scriptJobs,
    scriptVariants,
  );
  const manifest = OutputManifestSchema.parse({
    ...sourceManifest,
    mode: 'local_preview',
    script_jobs: scriptJobs,
    script_variants: scriptVariants,
    voice_over_jobs: voiceOverJobs,
    workflow_approvals: workflowApprovals,
    external_calls: {
      ...sourceManifest.external_calls,
      model: 'local_executed',
    },
    notes: [
      ...sourceManifest.notes,
      'Scripts were generated by a local Ollama model and require operator approval.',
      'TTS, rendering, asset downloads, and publishing remain disabled.',
    ],
  });

  const persistence = options.store ? await options.store.saveRun(manifest) : null;
  return { manifest, persistence, readiness };
}
